var latLongPoints = [

   
    { name: "Afghanistan", latitude: 33, longitude: 65 },
    { name: "Albania", latitude: 41, longitude: 20 },
    { name: "Algeria", latitude: 28, longitude: 3 },
    { name: "Argentina", latitude: -34, longitude: -64 },
    { name: "Australia", latitude: -27, longitude: 133 },
    { name: "Austria", latitude: 47.3333, longitude: 13.3333 },
    { name: "Azerbaijan", latitude: 40.5, longitude: 47.5 },
    { name: "Bangladesh", latitude: 24, longitude: 90 },
    { name: "Belarus", latitude: 53, longitude: 28 },
    { name: "Belgium", latitude: 50.8333, longitude: 4 },
    { name: "Belize", latitude: 17.25, longitude: -88.75 },
    { name: "Benin", latitude: 9.5, longitude: 2.25 },
    { name: "Bhutan", latitude: 27.5, longitude: 90.5 },
    { name: "Cambodia", latitude: 13, longitude: 105 },
    { name: "China", latitude: 35, longitude: 105 },
    { name: "Denmark", latitude: 56, longitude: 10 },
    { name: "Finland", latitude: 64, longitude: 26 },
    { name: "France", latitude: 46, longitude: 2 },
    { name: "Germany", latitude: 51, longitude: 9 },
    { name: "Greenland", latitude: 72, longitude: -40 },
    { name: "India", latitude: 20, longitude: 77 },
    { name: "Indonesia", latitude: -5, longitude: 120 },
    { name: "Japan", latitude: 36, longitude: 138 },
    { name: "Korea", latitude: 40, longitude: 127 },
    { name: "Netherlands", latitude: 52.5, longitude: 5.75 },
    { name: "New Zealand", latitude: -41, longitude: 174 },
    { name: "Pakistan", latitude: 30, longitude: 70 },
    { name: "South Africa", latitude: -29, longitude: 24 },
    { name: "Spain", latitude: 40, longitude: -4 },
    { name: "United States", latitude: 38, longitude: -97 }
    ];